version: 0.0
os: windows
files:
  - source: C:\MyConsoleapp\ConsoleApplication\ConsolePipeline
    destination: C:\ConsoleApp

hooks:
  ApplicationStart:
    - location: scripts\ApplicationStart.ps1
      timeout: 300
      runas: Administrator
